/*WIPE GAMES*/
DROP TABLE GAMES RESTART IDENTITY CASCADE;

/*WIPE TITLES*/
DROP TABLE TITLES RESTART IDENTITY CASCADE;

/*WIPE GENRES*/
DROP TABLE GENRES RESTART IDENTITY CASCADE;

/*WIPE PLATFORMS*/
DROP TABLE PLATFORMS RESTART IDENTITY CASCADE;

/*WIPE RATINGS*/
DROP TABLE RATINGS RESTART IDENTITY CASCADE;

/*WIPE AGES*/
DROP TABLE AGES RESTART IDENTITY CASCADE;

/*WIPE RELEASES*/
DROP TABLE RELEASES RESTART IDENTITY CASCADE;

/*WIPE DEVELOPERS*/
DROP TABLE DEVELOPERS RESTART IDENTITY CASCADE;
