/*WIPE GAMES*/
TRUNCATE TABLE GAMES RESTART IDENTITY CASCADE;

/*WIPE TITLES*/
TRUNCATE TABLE TITLES RESTART IDENTITY CASCADE;

/*WIPE GENRES*/
TRUNCATE TABLE GENRES RESTART IDENTITY CASCADE;

/*WIPE PLATFORMS*/
TRUNCATE TABLE PLATFORMS RESTART IDENTITY CASCADE;

/*WIPE RATINGS*/
TRUNCATE TABLE RATINGS RESTART IDENTITY CASCADE;

/*WIPE AGES*/
TRUNCATE TABLE AGES RESTART IDENTITY CASCADE;

/*WIPE RELEASES*/
TRUNCATE TABLE RELEASES RESTART IDENTITY CASCADE;

/*WIPE DEVELOPERS*/
TRUNCATE TABLE DEVELOPERS RESTART IDENTITY CASCADE;


